### ISSUE TITLE
Radar chart -  Uncaught TypeError

### ISSUE THREAD

**Issue by CarpeTempus** [dynamia-projects/chartjs-zk#1]
hi @marioserrano09 ,
first thank you for chartjs-zk - it is realy useful. I experienced that radar charts are not working as expected: the browser shows only "processing data" and thats it, the page never loads because the rendering of the chart never ends. In JavaScript Console there is an exception:
`tools.dynamia.chartjs.wpd:14 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.o.each (tools.dynamia.chartjs.wpd:14)
    at i.<anonymous> (tools.dynamia.chartjs.wpd:16)
    at Object.o.each (tools.dynamia.chartjs.wpd:14)
    at i.determineDataLimits (tools.dynamia.chartjs.wpd:16)
    at i.update (tools.dynamia.chartjs.wpd:15)
    at tools.dynamia.chartjs.wpd:15
    at Object.o.each (tools.dynamia.chartjs.wpd:14)
    at Object.update (tools.dynamia.chartjs.wpd:15)
    at t.Controller.updateLayout (tools.dynamia.chartjs.wpd:14)`

Since no documentation is available and the readme.md only points to www.dynamia.tools/chartjs-zk I tried to adopt the given information there. In my public ChartjsData getChartData() Function I have the following Code.

```
               CategoryChartjsData chartData = new CategoryChartjsData();
		Vector<String> v = new Vector<String>();
		

		List<Double> runs = new ArrayList<Double>();
		List<Double> members = new ArrayList<Double>();
		
		List<Project> projects = BeanUtil.svc().findAllProjects();
        for(Project p : projects)
        {
        	runs.add(new Double(p.getGenerationProcesses().size()));
        	members.add(new Double(p.getProjectmembersTotal()));
        	v.addElement(p.getName());
        }
        
        Dataset dataSetRuns = new Dataset("Members","rgba(255, 99, 132, 0.2)", runs);
        Dataset dataSetMembers = new Dataset("Generation Runs","rgba(54, 162, 235, 0.2)", members);
        // I tried it with new Dataset() aswell and used setData-method etc. to add the desired information but unfortunately without success
        // dataSetMembers, dataSetRuns and charData is shown as {} without attrubutes in Eclipse Debugger

        chartData.addDataset(dataSetMembers);
        chartData.addDataset(dataSetRuns);
        
        @SuppressWarnings("unchecked")
		String[] array = (String[]) v.toArray(new String[v.size()]);
        String labels = String.join(",", array);
        chartData.setLabels(labels);
        
        return chartData;
```

What am I doing wrong? Or is it a bug in chartjs-zk? Please help :-)

**Comment by marioserrano09** [comment]
Thanks for using this project we are currently retaking it and upgrading to latest Chartjs version. Its appear to be an error or bug in Chartjs-ZK, i am going to try replicate it and fix it. Please share zul part.

**Comment by CarpeTempus** [comment]
Thank you for your fast reply :) 
`<div sclass="col-xs-12 col-md-12">
							<chartjs sclass="col-xs-12 col-md-12" type="radar" title="Runs / Members" data="@bind(pvm.chartData3)"/>
						</div>`

**Comment by CarpeTempus** [comment]
Hi @marioserrano09 , any progress yet?

**Comment by marioserrano09** [comment]
Hi we are going to upload a new version this week please stay in touch.

**Comment by marioserrano09** [comment]
Check lastest version

**Comment by marioserrano09** [comment]
works in latest version. Check demo for example of using radar chart type
