### ISSUE TITLE
Version 2 not available in maven repositories

### ISSUE THREAD

**Issue by CarpeTempus** [dynamia-projects/chartjs-zk#4]
It is not possible to use this in pom.xml - maven can not resolve it:
<dependency>
    <groupId>tools.dynamia.chartjs</groupId>
    <artifactId>chartjs-zk</artifactId>
    <version>2.0.0</version>
</dependency>

Maven repository lists only version 1.0.0: 
https://mvnrepository.com/artifact/tools.dynamia.chartjs/chartjs-zk

Same with Maven central:
https://search.maven.org/#search%7Cga%7C1%7Ctools.dynamia.chartjs

**Comment by marioserrano09** [comment]
please wait for version 2.1.0 and new groupId will be tools.dynamia.zk.addons

**Comment by marioserrano09** [comment]
I just push a new version.. please help me test it and later i going to deploy to centra. Compile is just mvn clean install.

**Comment by marioserrano09** [comment]
Just uploaded version 2.7.1_R1 to maven central. Remember new groupId

```xml
<dependency>
    <groupId>tools.dynamia.zk.addons</groupId>
    <artifactId>chartjs-zk</artifactId>
    <version>2.7.2_R1</version>
</dependency>
```

Go here https://search.maven.org/search?q=tools.dynamia to check if artifact is synced
